- hosts: localhost
  vars:
    OSP_GUID: "{{ lookup('env','OSP_GUID') }}"
    OSP_DOMAIN: "{{ lookup('env','OSP_DOMAIN') }}"
    OPENTLC_ID: "{{ lookup('env','OPENTLC_ID') }}"

  tasks:
  - name: Create workstation inventory
    add_host:
       name: "workstation-{{OSP_GUID}}.{{OSP_DOMAIN}}"
       group: workstation
       ansible_user: "{{ OPENTLC_ID }}"

  - name: pause
    pause:
      minutes: 2


- hosts: workstation
  become: yes
  vars_files:
    - "group_vars/osp_vars.yml"
  roles:
    - osp-instance-delete
