---
# tasks file for osp-facts
- name: Fetch Instance Info
  os_server_info:
    cloud: openstack
    region_name: regionOne
  register: result

- debug:
    msg: "{{ item.metadata.group }} {{ item.metadata.deployment_name }}"
  loop: "{{ result.openstack_servers }}"

- name: Add host
  add_host:
    host: "{{ item.accessIPv4 }}"
    group:
      -  "{{ item.metadata.group }}"
    ansible_ssh_private_key_file: ~/.ssh/ansible_ssh
    ansible_ssh_user: cloud-user
  loop: "{{ result.openstack_servers }}"
  #delegate_to: workstation
  #register: group_result

- debug:
    var: groups



#- name: Add host
#  add_host:
#    name: "{{ item.public_v4 }}"
#    group: "{{ item.metadata.deployment_name }}"
#    ansible_ssh_private_key_file: ~/.ssh/openstack.pem
#    ansible_ssh_user: cloud-user
#  loop: "{{ result.openstack_servers }}"
  #delegate_to: workstation

